### ISSUE TITLE
enquiry to the coding of biplanar reconstruction

### ISSUE THREAD

**Issue by Bobby-scoilosis** [Beastmaster/Biplanar-reconstruction#1]
Greetings! I’m Bobby,  a research student from the Department of Biomedical Engineering at PolyU. 
We are working on a project about finite element analysis of the scoliotic spine and looking for the reconstruction methods using biplanar X-ray. I found a program written by you in 2017 satisfying our needs and I downloaded that from Github. However, when I tried to run this program in visual studio, I came across some problems(as attached). 
I searched for several methods trying to solve these problems, unfortunately, I failed. Could you please give me some hints? Thank you! 
![image](https://user-images.githubusercontent.com/74695572/102573788-35160700-412a-11eb-8d29-b888f4553d3e.png)

**Comment by Beastmaster** [comment]
Please follow routines that build a Qt+VTK program with CMake. This project implements some primary functions to stack 3d vertebra model. It's been a long time since I built the program and I have no time to provide further support. 
Really sorry

**Comment by Bobby-scoilosis** [comment]
> Please follow routines that build a Qt+VTK program with CMake. This project implements some primary functions to stack 3d vertebra model. It's been a long time since I built the program and I have no time to provide further support.
> Really sorry

Thank you for your suggestions and your program~~
